version: "3.8"

services:
  vollmed-api:
    container_name: voll.med.app
    image: voll.med.app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
