version: '3.8'

services:
  vollmed-api:
    build: .
    container_name: vollmed-app
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: vollmed-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: vollmed_api
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
